## Text summarization

In [1]:
import pandas as pd
import numpy as np
from transformers import pipeline

### loading the data

In [9]:
df = pd.read_csv('../text_summ_fine_tuning/Datasets/with_all_three/df_train.csv')
df.head()

,Unnamed: 0,headlines,text,ctext
0,0,Chhattisgarh to start ambulance service for cows,Chhattisgarh Chief Minister Raman Singh on Sun...,The Chhattisgarh government will begin an amb...
1,1,Trucks dumping debris on wetlands seized in Mu...,Mumbai Police on Saturday seized ten trucks an...,Ten trucks and an excavator machine that were ...
2,2,Modi pays homage to Indian World War I heroes ...,PM Narendra Modi visited the Haifa Indian Ceme...,On the last day of his three-day trip to Israe...
3,3,Delhi's domesticated elephants may be shifted ...,A forest department report submitted to the Hi...,Delhi could soon lose all its seven elephants ...
4,4,Ranchi civic body uses 'Sholay' climax to prom...,Ranchi Municipal Corporation has used movie Sh...,The Ranchi Nagar Nigam has upped the ante with...

In [10]:
print(f"{len(df['headlines'][0])} :: {len(df['text'][0])} :: {len(df['ctext'][0])}")

48 :: 359 :: 1549

In [11]:
df = df.head(4)

### without ctext

In [12]:
df

,Unnamed: 0,headlines,text,ctext
0,0,Chhattisgarh to start ambulance service for cows,Chhattisgarh Chief Minister Raman Singh on Sun...,The Chhattisgarh government will begin an amb...
1,1,Trucks dumping debris on wetlands seized in Mu...,Mumbai Police on Saturday seized ten trucks an...,Ten trucks and an excavator machine that were ...
2,2,Modi pays homage to Indian World War I heroes ...,PM Narendra Modi visited the Haifa Indian Ceme...,On the last day of his three-day trip to Israe...
3,3,Delhi's domesticated elephants may be shifted ...,A forest department report submitted to the Hi...,Delhi could soon lose all its seven elephants ...

In [13]:
df.drop(['Unnamed: 0', 'ctext'], axis = 1, inplace = True)
df

,headlines,text
0,Chhattisgarh to start ambulance service for cows,Chhattisgarh Chief Minister Raman Singh on Sun...
1,Trucks dumping debris on wetlands seized in Mu...,Mumbai Police on Saturday seized ten trucks an...
2,Modi pays homage to Indian World War I heroes ...,PM Narendra Modi visited the Haifa Indian Ceme...
3,Delhi's domesticated elephants may be shifted ...,A forest department report submitted to the Hi...

### model 1

In [14]:
pipeline_1 = pipeline('summarization', model = 'sshleifer/distilbart-cnn-12-6')

c:\Users\lenovo\anaconda3\envs\tfenv\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\lenovo\.cache\huggingface\hub\models--sshleifer--distilbart-cnn-12-6. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Device set to use cpu

In [21]:
summary_1 = []
for i in range(0, 4) : 
    summary = pipeline_1(df['text'][i], max_length = 20, min_length = 10, do_sample = False)
    print(f"context : {df['text'][i]}")
    print(f"ref summary : {df['headlines'][i]}")
    print(f"generated summary : {summary}")

    print('*'* 40)


    summary_1.append(summary)

context : Chhattisgarh Chief Minister Raman Singh on Sunday announced that ambulance service for cows will be started in 10 districts of the state over the next few months. He also urged people to support organic farming and biogas in order to promote a cow-based economy. Earlier this year, Singh had said that anyone found killing cows in Chhattisgarh will be hanged.
ref summary : Chhattisgarh to start ambulance service for cows
generated summary : [{'summary_text': ' Chhattisgarh Chief Minister Raman Singh announced that ambulance service for cows will'}]
****************************************
context : Mumbai Police on Saturday seized ten trucks and an excavator machine for allegedly dumping debris at a 400-acre wetland area in Andheri. Twelve people have been detained for the alleged environment violation and were fined ?60,000, police officials said. The dumping of debris has reportedly destroyed a two-acre patch at the wetland.
ref summary : Trucks dumping debris on wetlands seized in Mumbai
generated summary : [{'summary_text': ' Twelve people have been detained for the alleged environment violation and fined ?60,000 .'}]
****************************************
context : PM Narendra Modi visited the Haifa Indian Cemetery in Israel today and paid his homage to  Indian soldiers who laid down their lives during the World War I in 1918. "I am deeply honoured to stand here today to salute the valiant Indian soldiers," Modi said. The war heroes died while protecting Haifa from the forces of the Ottoman Empire.
ref summary : Modi pays homage to Indian World War I heroes in Israel
generated summary : [{'summary_text': ' PM Narendra Modi visited the Haifa Indian Cemetery in Israel to pay tribute to Indian soldiers'}]
****************************************
context : A forest department report submitted to the High Court suggested that all the seven domesticated elephants of Delhi be shifted to a sanctuary outside the city. It observed that not only were the elephants kept in poor conditions, but it was also risky to house them in crowded localities. Most of the elephants don't have proper ownership certificates, report said.
ref summary : Delhi's domesticated elephants may be shifted to a sanctuary
generated summary : [{'summary_text': ' A forest department report submitted to the High Court suggested that all the seven domesticated elephants'}]
****************************************

### model 2

In [17]:
pipeline_2 = pipeline('summarization', model = 'facebook/bart-large-cnn')

Device set to use cpu

In [24]:
summary_2 = []
for i in range(0, 4) : 
    summary = pipeline_2(df['text'][i], min_length = 10, max_length = 20, do_sample = False)
    print(f"text : {df['text'][i]}")
    print(f"ref summary : {df['headlines'][i]}")
    print(f"gen summary : {summary}")

    print('*'* 40)

    summary_2.append(summary)

text : Chhattisgarh Chief Minister Raman Singh on Sunday announced that ambulance service for cows will be started in 10 districts of the state over the next few months. He also urged people to support organic farming and biogas in order to promote a cow-based economy. Earlier this year, Singh had said that anyone found killing cows in Chhattisgarh will be hanged.
ref summary : Chhattisgarh to start ambulance service for cows
gen summary : [{'summary_text': 'Chhattisgarh Chief Minister Raman Singh announced that ambulance service for cows will'}]
****************************************
text : Mumbai Police on Saturday seized ten trucks and an excavator machine for allegedly dumping debris at a 400-acre wetland area in Andheri. Twelve people have been detained for the alleged environment violation and were fined ?60,000, police officials said. The dumping of debris has reportedly destroyed a two-acre patch at the wetland.
ref summary : Trucks dumping debris on wetlands seized in Mumbai
gen summary : [{'summary_text': 'Mumbai Police seized ten trucks and an excavator machine for allegedly dumping debris at a'}]
****************************************
text : PM Narendra Modi visited the Haifa Indian Cemetery in Israel today and paid his homage to  Indian soldiers who laid down their lives during the World War I in 1918. "I am deeply honoured to stand here today to salute the valiant Indian soldiers," Modi said. The war heroes died while protecting Haifa from the forces of the Ottoman Empire.
ref summary : Modi pays homage to Indian World War I heroes in Israel
gen summary : [{'summary_text': 'PM Narendra Modi visited the Haifa Indian Cemetery in Israel today. He paid his homage'}]
****************************************
text : A forest department report submitted to the High Court suggested that all the seven domesticated elephants of Delhi be shifted to a sanctuary outside the city. It observed that not only were the elephants kept in poor conditions, but it was also risky to house them in crowded localities. Most of the elephants don't have proper ownership certificates, report said.
ref summary : Delhi's domesticated elephants may be shifted to a sanctuary
gen summary : [{'summary_text': 'A forest department report submitted to the High Court suggested that all the seven domesticated elephants'}]
****************************************

In [22]:
summary_1

[[{'summary_text': ' Chhattisgarh Chief Minister Raman Singh announced that ambulance service for cows will'}],
 [{'summary_text': ' Twelve people have been detained for the alleged environment violation and fined ?60,000 .'}],
 [{'summary_text': ' PM Narendra Modi visited the Haifa Indian Cemetery in Israel to pay tribute to Indian soldiers'}],
 [{'summary_text': ' A forest department report submitted to the High Court suggested that all the seven domesticated elephants'}]]

In [25]:
summary_2

[[{'summary_text': 'Chhattisgarh Chief Minister Raman Singh announced that ambulance service for cows will'}],
 [{'summary_text': 'Mumbai Police seized ten trucks and an excavator machine for allegedly dumping debris at a'}],
 [{'summary_text': 'PM Narendra Modi visited the Haifa Indian Cemetery in Israel today. He paid his homage'}],
 [{'summary_text': 'A forest department report submitted to the High Court suggested that all the seven domesticated elephants'}]]