## Text Summarization

In [1]:
import pandas as pd
import numpy as np
from transformers import pipeline

### loading the data

In [3]:
df = pd.read_csv('news_summary_more.csv')
df.head()

,headlines,text
0,upGrad learner switches to career in ML & Al w...,"Saurav Kant, an alumnus of upGrad and IIIT-B's..."
1,Delhi techie wins free food from Swiggy for on...,Kunal Shah's credit card bill payment platform...
2,New Zealand end Rohit Sharma-led India's 12-ma...,New Zealand defeated India by 8 wickets in the...
3,Aegon life iTerm insurance plan helps customer...,"With Aegon Life iTerm Insurance plan, customer..."
4,"Have known Hirani for yrs, what if MeToo claim...",Speaking about the sexual harassment allegatio...

In [4]:
df = df.head(10)

In [5]:
df

,headlines,text
0,upGrad learner switches to career in ML & Al w...,"Saurav Kant, an alumnus of upGrad and IIIT-B's..."
1,Delhi techie wins free food from Swiggy for on...,Kunal Shah's credit card bill payment platform...
2,New Zealand end Rohit Sharma-led India's 12-ma...,New Zealand defeated India by 8 wickets in the...
3,Aegon life iTerm insurance plan helps customer...,"With Aegon Life iTerm Insurance plan, customer..."
4,"Have known Hirani for yrs, what if MeToo claim...",Speaking about the sexual harassment allegatio...
5,Rahat Fateh Ali Khan denies getting notice for...,Pakistani singer Rahat Fateh Ali Khan has deni...
6,"India get all out for 92, their lowest ODI tot...",India recorded their lowest ODI total in New Z...
7,Govt directs Alok Verma to join work 1 day bef...,Weeks after ex-CBI Director Alok Verma told th...
8,Called PM Modi 'sir' 10 times to satisfy his e...,Andhra Pradesh CM N Chandrababu Naidu has said...
9,"Cong wins Ramgarh bypoll in Rajasthan, takes t...",Congress candidate Shafia Zubair won the Ramga...

In [6]:
df['headlines'][0]

'upGrad learner switches to career in ML & Al with 90% salary hike'

### model 1

In [7]:
model_1 = pipeline('summarization', model = 'sshleifer/distilbart-cnn-12-6')

Device set to use cpu

In [9]:
gen_summary = []
for i in range(0, 10) : 
    summary = model_1(df['text'][i], min_length = 12, max_length = 15, do_sample = False)
    gen_summary.append(summary)

    print(f"text : {df['text'][i]}")
    print(f"ref summary : {df['headlines'][i]}")
    print(f"gen summary : {summary}")

    print('*'*50)

text : Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers.
ref summary : upGrad learner switches to career in ML & Al with 90% salary hike
gen summary : [{'summary_text': " upGrad's Online Power Learning has powered 3 lakh+ careers"}]
**************************************************
text : Kunal Shah's credit card bill payment platform, CRED, gave users a chance to win free food from Swiggy for one year. Pranav Kaushik, a Delhi techie, bagged this reward after spending 2000 CRED coins. Users get one CRED coin per rupee of bill paid, which can be used to avail rewards from brands like Ixigo, BookMyShow, UberEats, Cult.Fit and more.
ref summary : Delhi techie wins free food from Swiggy for one year on CRED
gen summary : [{'summary_text': " Kunal Shah's credit card bill payment platform, CRED"}]
**************************************************
text : New Zealand defeated India by 8 wickets in the fourth ODI at Hamilton on Thursday to win their first match of the five-match ODI series. India lost an international match under Rohit Sharma's captaincy after 12 consecutive victories dating back to March 2018. The match witnessed India getting all out for 92, their seventh lowest total in ODI cricket history.
ref summary : New Zealand end Rohit Sharma-led India's 12-match winning streak
gen summary : [{'summary_text': " India lost an international match under Rohit Sharma's captaincy"}]
**************************************************
text : With Aegon Life iTerm Insurance plan, customers can enjoy tax benefits on your premiums paid and save up to â¹46,800^ on taxes. The plan provides life cover up to the age of 100 years. Also, customers have options to insure against Critical Illnesses, Disability and Accidental Death Benefit Rider with a life cover up to the age of 80 years.
ref summary : Aegon life iTerm insurance plan helps customers save tax
gen summary : [{'summary_text': ' Aegon Life iTerm Insurance plan provides life cover up to'}]
**************************************************
text : Speaking about the sexual harassment allegations against Rajkumar Hirani, Sonam Kapoor said, "I've known Hirani for many years...What if it's not true, the [#MeToo] movement will get derailed." "In the #MeToo movement, I always believe a woman. But in this case, we need to reserve our judgment," she added. Hirani has been accused by an assistant who worked in 'Sanju'.
ref summary : Have known Hirani for yrs, what if MeToo claims are not true: Sonam
gen summary : [{'summary_text': ' Sonam Kapoor has known Rajkumar Hirani for'}]
**************************************************
text : Pakistani singer Rahat Fateh Ali Khan has denied receiving any notice from the Enforcement Directorate over allegedly smuggling foreign currency out of India. "It would have been better if the authorities would have served the notice first if any and then publicised this," reads a press release issued on behalf of Rahat. The statement further called the allegation "bizarre".
ref summary : Rahat Fateh Ali Khan denies getting notice for smuggling currency
gen summary : [{'summary_text': ' Rahat Fateh Ali Khan has denied receiving any notice from'}]
**************************************************
text : India recorded their lowest ODI total in New Zealand after getting all out for 92 runs in 30.5 overs in the fourth ODI at Hamilton on Thursday. Seven of India's batsmen were dismissed for single-digit scores, while their number ten batsman Yuzvendra Chahal top-scored with 18*(37). India's previous lowest ODI total in New Zealand was 108.
ref summary : India get all out for 92, their lowest ODI total in New Zealand
gen summary : [{'summary_text': ' India recorded their lowest ODI total in New Zealand after getting'}]
**************************************************
text : Weeks after ex-CBI Director Alok Verma told the Department of Personnel and Training to consider him retired, the Home Ministry asked him to join work on the last day of his fixed tenure as Director on Thursday. The ministry directed him to immediately join as DG, Fire Services, the post he was transferred to after his removal as CBI chief.
ref summary : Govt directs Alok Verma to join work 1 day before his retirement
gen summary : [{'summary_text': ' Home Ministry asked him to join work on the last day of'}]
**************************************************
text : Andhra Pradesh CM N Chandrababu Naidu has said, "When I met then US President Bill Clinton, I addressed him as Mr Clinton, not as 'sir'. (PM Narendra) Modi is my junior in politics...I addressed him as sir 10 times." "I did this...to satisfy his ego in the hope that he will do justice to the state," he added.
ref summary : Called PM Modi 'sir' 10 times to satisfy his ego: Andhra CM
gen summary : [{'summary_text': ' Andhra Pradesh CM N Chandrabababu Naid'}]
**************************************************
text : Congress candidate Shafia Zubair won the Ramgarh Assembly seat in Rajasthan, by defeating BJP's Sukhwant Singh with a margin of 12,228 votes in the bypoll. With this victory, Congress has taken its total to 100 seats in the 200-member assembly. The election to the Ramgarh seat was delayed due to the death of sitting MLA and BSP candidate Laxman Singh.
ref summary : Cong wins Ramgarh bypoll in Rajasthan, takes total to 100 seats
gen summary : [{'summary_text': ' Congress candidate Shafia Zubair won the Ramgarh Assembly'}]
**************************************************

### model 2

In [11]:
model_2 = pipeline('summarization', model = 'facebook/bart-large-cnn')

Device set to use cpu

In [12]:
gen_summary_2 = []
for i in range(0, 10) : 
    summary = model_2(df['text'][i], min_length = 12, max_length = 15, do_sample = False)
    gen_summary_2.append(summary)

    print(f"text : {df['text'][i]}")
    print(f"ref summary : {df['headlines'][i]}")
    print(f"gen summary : {summary}")

    print('*'*50)

text : Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers.
ref summary : upGrad learner switches to career in ML & Al with 90% salary hike
gen summary : [{'summary_text': 'Saurav Kant, an alumnus of upGrad'}]
**************************************************
text : Kunal Shah's credit card bill payment platform, CRED, gave users a chance to win free food from Swiggy for one year. Pranav Kaushik, a Delhi techie, bagged this reward after spending 2000 CRED coins. Users get one CRED coin per rupee of bill paid, which can be used to avail rewards from brands like Ixigo, BookMyShow, UberEats, Cult.Fit and more.
ref summary : Delhi techie wins free food from Swiggy for one year on CRED
gen summary : [{'summary_text': "Kunal Shah's credit card bill payment platform, CRED"}]
**************************************************
text : New Zealand defeated India by 8 wickets in the fourth ODI at Hamilton on Thursday to win their first match of the five-match ODI series. India lost an international match under Rohit Sharma's captaincy after 12 consecutive victories dating back to March 2018. The match witnessed India getting all out for 92, their seventh lowest total in ODI cricket history.
ref summary : New Zealand end Rohit Sharma-led India's 12-match winning streak
gen summary : [{'summary_text': 'New Zealand defeated India by 8 wickets in the fourth O'}]
**************************************************
text : With Aegon Life iTerm Insurance plan, customers can enjoy tax benefits on your premiums paid and save up to â¹46,800^ on taxes. The plan provides life cover up to the age of 100 years. Also, customers have options to insure against Critical Illnesses, Disability and Accidental Death Benefit Rider with a life cover up to the age of 80 years.
ref summary : Aegon life iTerm insurance plan helps customers save tax
gen summary : [{'summary_text': 'With Aegon Life iTerm Insurance plan, customers can enjoy'}]
**************************************************
text : Speaking about the sexual harassment allegations against Rajkumar Hirani, Sonam Kapoor said, "I've known Hirani for many years...What if it's not true, the [#MeToo] movement will get derailed." "In the #MeToo movement, I always believe a woman. But in this case, we need to reserve our judgment," she added. Hirani has been accused by an assistant who worked in 'Sanju'.
ref summary : Have known Hirani for yrs, what if MeToo claims are not true: Sonam
gen summary : [{'summary_text': 'Rajkumar Hirani has been accused of sexual harassment'}]
**************************************************
text : Pakistani singer Rahat Fateh Ali Khan has denied receiving any notice from the Enforcement Directorate over allegedly smuggling foreign currency out of India. "It would have been better if the authorities would have served the notice first if any and then publicised this," reads a press release issued on behalf of Rahat. The statement further called the allegation "bizarre".
ref summary : Rahat Fateh Ali Khan denies getting notice for smuggling currency
gen summary : [{'summary_text': 'Rahat Fateh Ali Khan has denied receiving any notice from'}]
**************************************************
text : India recorded their lowest ODI total in New Zealand after getting all out for 92 runs in 30.5 overs in the fourth ODI at Hamilton on Thursday. Seven of India's batsmen were dismissed for single-digit scores, while their number ten batsman Yuzvendra Chahal top-scored with 18*(37). India's previous lowest ODI total in New Zealand was 108.
ref summary : India get all out for 92, their lowest ODI total in New Zealand
gen summary : [{'summary_text': 'India recorded their lowest ODI total in New Zealand after getting'}]
**************************************************
text : Weeks after ex-CBI Director Alok Verma told the Department of Personnel and Training to consider him retired, the Home Ministry asked him to join work on the last day of his fixed tenure as Director on Thursday. The ministry directed him to immediately join as DG, Fire Services, the post he was transferred to after his removal as CBI chief.
ref summary : Govt directs Alok Verma to join work 1 day before his retirement
gen summary : [{'summary_text': 'The Home Ministry asked him to join work on the last day'}]
**************************************************
text : Andhra Pradesh CM N Chandrababu Naidu has said, "When I met then US President Bill Clinton, I addressed him as Mr Clinton, not as 'sir'. (PM Narendra) Modi is my junior in politics...I addressed him as sir 10 times." "I did this...to satisfy his ego in the hope that he will do justice to the state," he added.
ref summary : Called PM Modi 'sir' 10 times to satisfy his ego: Andhra CM
gen summary : [{'summary_text': 'Andhra Pradesh CM N Chandrababu Naidu'}]
**************************************************
text : Congress candidate Shafia Zubair won the Ramgarh Assembly seat in Rajasthan, by defeating BJP's Sukhwant Singh with a margin of 12,228 votes in the bypoll. With this victory, Congress has taken its total to 100 seats in the 200-member assembly. The election to the Ramgarh seat was delayed due to the death of sitting MLA and BSP candidate Laxman Singh.
ref summary : Cong wins Ramgarh bypoll in Rajasthan, takes total to 100 seats
gen summary : [{'summary_text': 'Congress candidate Shafia Zubair won the Ramgarh Assembly'}]
**************************************************

In [13]:
gen_summary

[[{'summary_text': " upGrad's Online Power Learning has powered 3 lakh+ careers"}],
 [{'summary_text': " Kunal Shah's credit card bill payment platform, CRED"}],
 [{'summary_text': " India lost an international match under Rohit Sharma's captaincy"}],
 [{'summary_text': ' Aegon Life iTerm Insurance plan provides life cover up to'}],
 [{'summary_text': ' Sonam Kapoor has known Rajkumar Hirani for'}],
 [{'summary_text': ' Rahat Fateh Ali Khan has denied receiving any notice from'}],
 [{'summary_text': ' India recorded their lowest ODI total in New Zealand after getting'}],
 [{'summary_text': ' Home Ministry asked him to join work on the last day of'}],
 [{'summary_text': ' Andhra Pradesh CM N Chandrabababu Naid'}],
 [{'summary_text': ' Congress candidate Shafia Zubair won the Ramgarh Assembly'}]]

In [14]:
gen_summary_2

[[{'summary_text': 'Saurav Kant, an alumnus of upGrad'}],
 [{'summary_text': "Kunal Shah's credit card bill payment platform, CRED"}],
 [{'summary_text': 'New Zealand defeated India by 8 wickets in the fourth O'}],
 [{'summary_text': 'With Aegon Life iTerm Insurance plan, customers can enjoy'}],
 [{'summary_text': 'Rajkumar Hirani has been accused of sexual harassment'}],
 [{'summary_text': 'Rahat Fateh Ali Khan has denied receiving any notice from'}],
 [{'summary_text': 'India recorded their lowest ODI total in New Zealand after getting'}],
 [{'summary_text': 'The Home Ministry asked him to join work on the last day'}],
 [{'summary_text': 'Andhra Pradesh CM N Chandrababu Naidu'}],
 [{'summary_text': 'Congress candidate Shafia Zubair won the Ramgarh Assembly'}]]