## Q&A play with models

In [1]:
import pandas as pd
import numpy as np
from transformers import pipeline

### loading the context

In [4]:
import os
path = '../text_summarization'
files = os.listdir(path)
print(files)

['first.ipynb', 'logs', 'logs_3', 'logs_4', 'logs_5', 'news_summary.csv', 'news_summary_more.csv', 'results', 'results_3', 'results_4', 'results_5', 'second.ipynb', 'summary_1.ipynb', 'summary_3.ipynb', 'summary_4.ipynb', 'summary_5.ipynb', 'summar_2.ipynb']

In [5]:
df = pd.read_csv(path + '/news_summary.csv')
df.head()

,author,date,headlines,read_more,text,ctext
0,Chhavi Tyagi,"03 Aug 2017,Thursday",Daman & Diu revokes mandatory Rakshabandhan in...,http://www.hindustantimes.com/india-news/raksh...,The Administration of Union Territory Daman an...,The Daman and Diu administration on Wednesday ...
1,Daisy Mowke,"03 Aug 2017,Thursday",Malaika slams user who trolled her for 'divorc...,http://www.hindustantimes.com/bollywood/malaik...,Malaika Arora slammed an Instagram user who tr...,"From her special numbers to TV?appearances, Bo..."
2,Arshiya Chopra,"03 Aug 2017,Thursday",'Virgin' now corrected to 'Unmarried' in IGIMS...,http://www.hindustantimes.com/patna/bihar-igim...,The Indira Gandhi Institute of Medical Science...,The Indira Gandhi Institute of Medical Science...
3,Sumedha Sehra,"03 Aug 2017,Thursday",Aaj aapne pakad liya: LeT man Dujana before be...,http://indiatoday.intoday.in/story/abu-dujana-...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...
4,Aarushi Maheshwari,"03 Aug 2017,Thursday",Hotel staff to get training to spot signs of s...,http://indiatoday.intoday.in/story/sex-traffic...,Hotels in Maharashtra will train their staff t...,Hotels in Mumbai and other Indian cities are t...

In [6]:
df.tail()

,author,date,headlines,read_more,text,ctext
4509,Mansha Mahajan,"24 Feb 2017,Friday",Rasna seeking ?250 cr revenue from snack categ...,http://indiatoday.intoday.in/story/rasna-eyes-...,Fruit juice concentrate maker Rasna is eyeing ...,"Mumbai, Feb 23 (PTI) Fruit juice concentrate m..."
4510,Dishant Sharma,"03 Aug 2017,Thursday",Sachin attends Rajya Sabha after questions on ...,http://indiatoday.intoday.in/story/sachin-tend...,Former Indian cricketer Sachin Tendulkar atten...,Former cricketer Sachin Tendulkar was spotted ...
4511,Tanya Dhingra,"03 Aug 2017,Thursday",Shouldn't rob their childhood: Aamir on kids r...,http://www.hindustantimes.com/bollywood/secret...,"Aamir Khan, while talking about reality shows ...","Aamir Khan, whose last film Dangal told the st..."
4512,Pragya Swastik,"07 Dec 2016,Wednesday","Asha Bhosle gets ?53,000 power bill for unused...",http://indiatoday.intoday.in/story/singer-asha...,The Maharashtra government has initiated an in...,Maharahstra Power Minister Chandrashekhar Bawa...
4513,Chhavi Tyagi,"03 Aug 2017,Thursday",More than half of India's languages may die in...,http://indiatoday.intoday.in/story/indian-lang...,At least 400 languages or more than half langu...,More than half of the languages spoken by Indi...

In [7]:
context = df['ctext'][4510]
print(context)

Former cricketer Sachin Tendulkar was spotted in the Rajya Sabha today a couple of days after absence of nominated members from the Upper House was questioned by Samajwadi Party MP Naresh Agarwal.Although Sachin attended Rajya Sabha proceedings, he didn't ask any question. Boxer Mary Kom too was present in the House today.Samajwadi Party MP Naresh Agarwal had on Tuesday questioned the absence of celebrity members of the House and advocated them being disqualified from Rajya Sabha membership."Sachin Tendulkar and Rekha should resign if they are not interested in Parliament," Agarwal said.Tendulkar and actor Rekha were the worst performers in attendance in the Rajya Sabha among the 12 nominated members.Besides Tendulkar and Rekha, other nominated members include Anu Aga, Sambhaji Chhatrapati, Swapan Dasgupta, Roopa Ganguly, Narendra Jadhav, M C Mary Kom, K Parasaran, Gopi Suresh, Subramanian Swamy and KTS Tulsi.ALSO READ:

### generating questions

In [28]:
gen_qa = pipeline('text2text-generation', model = 'iarfmoose/t5-base-question-generator')

Device set to use cpu

In [29]:
i = 0

while i < 5:

    gen_questions = gen_qa(context, max_length = 32, num_return_sequences = 3, do_sample = True, top_k = 50, top_p = 0.95, temperature = 0.8)
    for q in gen_questions : 
        first, last = q['generated_text'].split("?", 1)
        print(first)

    i += 1

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today
Who was present in the Rajya Sabha today

### trying with the different context

In [31]:
context = """
          Australia won the 2023 world cup, this cricket world cup was hosted by India,
          India and Australia played the final in Ahemdabad, Narendra modi stadium,
          Australian skipper Pat Cummins won the toss and decided to bowl first, where 
          They managed to restrict India to a small total score of 240, and then Austrlia won the final in 
          a convinving victory with Travis head scoring 140, and by 6 wickets in hand, It was Australia's sixth world cup win,
          after 1987, 1999, 2003, 2007 and 2015, making the Australia number 1 ranked team in cricket.
          """

In [33]:
i = 0

while i < 5:

    gen_questions = gen_qa(context, max_length = 32, num_return_sequences = 3, do_sample = True, top_k = 50, top_p = 0.95, temperature = 0.8)
    for q in gen_questions : 
        first, last = q['generated_text'].split("?", 1)
        print(first)

    i += 1

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

How did Australia win the world cup in 2023
How did Australia win the world cup in 2023
How did Australia win the world cup in 2023

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

How did Australia win the world cup in 2023
How did Australia win the world cup in 2023
How did Australia win the world cup in 2023

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

What year did Australia win the world cup
What year did Australia win the cricket world cup
What year did Australia win the world cup in 2023

Both `max_new_tokens` (=256) and `max_length`(=32) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

How did Australia win the world cup in 2023
How did Australia win the world cup in 2023
How did Australia win the world cup in 2023
What year did Australia win the world cup
What year did Australia win the cricket world cup
What year did Australia win the world cup